### PR TITLE
Dev mode

### PR DESCRIPTION
**Pull request by webcoderz**
adding dev mode , dev cluster ci and fixing gak port mapping

### CODE REVIEW

**Review by lmeyerov — APPROVED** [review]
lgtm, but then again, not the best here yet

**Comment by lmeyerov** [comment]
@webcoderz should we be landing this PR as it's growing quite large?

as part of that, azure pipelines seems to be failing on it: https://graphistry.slack.com/archives/D02Q4SZ81N2/p1654800986419379

**Comment by lmeyerov** [comment]
fix az pipeline stuff & merge?

**Comment by webcoderz** [comment]
https://github.com/graphistry/graphistry-helm/blob/7fb3d6e78ae4987a3b6e12cd2857d44dab20b505/acr-bootstrap/import-image-into-acr-from-dockerhub.sh#L71 yea here's where gak is imported , we started adding cuda tag on 2.39.13 should I add some logic in here to take non cuda tag into account? Also need to delete/comment out redis from delete acr containers script also

**Comment by lmeyerov** [comment]
> should I add some logic in here to take non cuda tag into account

streamlit container can assume cuda tag for now, let's get single node solid before worrying about multi-node (where streamlit might be cpu)

**Pull request merged**
